import React from 'react';
import PDF  from '../../assets/svg/fileIcons/pdf.svg'
import ThreeDS  from '../../assets/svg/fileIcons/3ds.svg'
import AI  from '../../assets/svg/fileIcons/ai.svg'
import ASP  from '../../assets/svg/fileIcons/asp.svg'
import AVI  from '../../assets/svg/fileIcons/avi.svg'
import BIN  from '../../assets/svg/fileIcons/bin.svg'
import COM  from '../../assets/svg/fileIcons/com.svg'
import CSS  from '../../assets/svg/fileIcons/css.svg'
import CSV  from '../../assets/svg/fileIcons/csv.svg'
import DBF  from '../../assets/svg/fileIcons/dbf.svg'
import DLL  from '../../assets/svg/fileIcons/dll.svg'
import DOC  from '../../assets/svg/fileIcons/doc.svg'
import DWG  from '../../assets/svg/fileIcons/dwg.svg'
import EML  from '../../assets/svg/fileIcons/eml.svg'
import EPS  from '../../assets/svg/fileIcons/eps.svg'
// import PDF  from '../../assets/svg/fileIcons/pdf.svg'
// import PDF  from '../../assets/svg/fileIcons/pdf.svg'
// import PDF  from '../../assets/svg/fileIcons/pdf.svg'
// import PDF  from '../../assets/svg/fileIcons/pdf.svg'
// import PDF  from '../../assets/svg/fileIcons/pdf.svg'
// import PDF  from '../../assets/svg/fileIcons/pdf.svg'
// import PDF  from '../../assets/svg/fileIcons/pdf.svg'
// import PDF  from '../../assets/svg/fileIcons/pdf.svg'
// import PDF  from '../../assets/svg/fileIcons/pdf.svg'
// import PDF  from '../../assets/svg/fileIcons/pdf.svg'
// import PDF  from '../../assets/svg/fileIcons/pdf.svg'
// import PDF  from '../../assets/svg/fileIcons/pdf.svg'
// import PDF  from '../../assets/svg/fileIcons/pdf.svg'
// import PDF  from '../../assets/svg/fileIcons/pdf.svg'
// import PDF  from '../../assets/svg/fileIcons/pdf.svg'
// import PDF  from '../../assets/svg/fileIcons/pdf.svg'
// import PDF  from '../../assets/svg/fileIcons/pdf.svg'
// import PDF  from '../../assets/svg/fileIcons/pdf.svg'
// import PDF  from '../../assets/svg/fileIcons/pdf.svg'
// import PDF  from '../../assets/svg/fileIcons/pdf.svg'
// import PDF  from '../../assets/svg/fileIcons/pdf.svg'
// import PDF  from '../../assets/svg/fileIcons/pdf.svg'
// import PDF  from '../../assets/svg/fileIcons/pdf.svg'
// import PDF  from '../../assets/svg/fileIcons/pdf.svg'
// import PDF  from '../../assets/svg/fileIcons/pdf.svg'
// import PDF  from '../../assets/svg/fileIcons/pdf.svg'
// import PDF  from '../../assets/svg/fileIcons/pdf.svg'
// import PDF  from '../../assets/svg/fileIcons/pdf.svg'
// import PDF  from '../../assets/svg/fileIcons/pdf.svg'
// import PDF  from '../../assets/svg/fileIcons/pdf.svg'
// import PDF  from '../../assets/svg/fileIcons/pdf.svg'
// import PDF  from '../../assets/svg/fileIcons/pdf.svg'
// import PDF  from '../../assets/svg/fileIcons/pdf.svg'
// import PDF  from '../../assets/svg/fileIcons/pdf.svg'
// import PDF  from '../../assets/svg/fileIcons/pdf.svg'


const  fileType=[
  'pdf','word','doc'
]
 
const FileIcons  = ({fileType}, ...props) => {

}
 
export default FileIcons