export const CHANGE_SCREEN = 'CHANGE_SCREEN';
export const GET_ALL_DEPARTMENTS_BEGIN = 'GET_ALL_DEPARTMENTS_BEGIN'
export const GET_ALL_DEPARTMENTS_ERROR = 'GET_ALL_DEPARTMENTS_ERROR'
export const GET_ALL_DEPARTMENTS_SUCCESS = 'GET_ALL_DEPARTMENTS_SUCCESS'
export const SET_FILTER_DEPARTMENTS = 'SET_FILTER_DEPARTMENTS'
export const GET_DEPARTMENT_LEVELS_BEGIN = 'GET_DEPARTMENT_LEVELS_BEGIN'
export const GET_DEPARTMENT_LEVELS_ERROR = 'GET_DEPARTMENT_LEVELS_ERROR'
export const GET_DEPARTMENT_LEVELS_SUCCESS = 'GET_DEPARTMENT_LEVELS_SUCCESS'