export const CHANGE_SCREEN = 'CHANGE_SCREEN';
export const GET_ALL_DEPARTMENTS_BEGIN = 'GET_ALL_DEPARTMENTS_BEGIN'
export const GET_ALL_DEPARTMENTS_ERROR = 'GET_ALL_DEPARTMENTS_ERROR'
export const GET_ALL_DEPARTMENTS_SUCCESS = 'GET_ALL_DEPARTMENTS_SUCCESS'
export const SET_FILTER_DEPARTMENTS = 'SET_DEPARTMENTS'