import { Platform } from "react-native";

export const CHANGE_SCREEN = 'CHANGE_SCREEN';
export const GET_ALL_DEPARTMENTS_BEGIN = 'GET_ALL_DEPARTMENTS_BEGIN'
export const GET_ALL_DEPARTMENTS_ERROR = 'GET_ALL_DEPARTMENTS_ERROR'
export const GET_ALL_DEPARTMENTS_SUCCESS = 'GET_ALL_DEPARTMENTS_SUCCESS'
export const SET_FILTER_DEPARTMENTS = 'SET_FILTER_DEPARTMENTS'
export const GET_DEPARTMENT_LEVELS_BEGIN = 'GET_DEPARTMENT_LEVELS_BEGIN'
export const GET_DEPARTMENT_LEVELS_ERROR = 'GET_DEPARTMENT_LEVELS_ERROR'
export const GET_DEPARTMENT_LEVELS_SUCCESS = 'GET_DEPARTMENT_LEVELS_SUCCESS'
export const GET_MATERIALS_BEGIN = 'GET_MATERIALS_BEGIN'
export const GET_MATERIALS_ERROR = 'GET_MATERIALS_ERROR'
export const GET_MATERIALS_SUCCESS = 'GET_MATERIALS_SUCCESS'
export const GET_ATTENDANCE_BEGIN = 'GET_ATTENDANCE_BEGIN'
export const GET_ATTENDANCE_ERROR = 'GET_ATTENDANCE_ERROR'
export const GET_ATTENDANCE_SUCCESS = 'GET_ATTENDANCE_SUCCESS'
export const MATERIALS_SEARCH_BEGIN = 'MATERIALS_SEARCH_BEGIN'
export const MATERIALS_SEARCH_ERROR = 'MATERIALS_SEARCH_ERROR'
export const MATERIALS_SEARCH_SUCCESS = 'MATERIALS_SEARCH_SUCCESS'
export const GET_BLOGS_BEGIN = 'GET_BLOGS_BEGIN'
export const GET_BLOGS_ERROR = 'GET_BLOGS_ERROR'
export const GET_BLOGS_SUCCESS = 'GET_BLOGS_SUCCESS'
export const GET_TIMETABLE_BEGIN = 'GET_TIMETABLE_BEGIN'
export const GET_TIMETABLE_ERROR = 'GET_TIMETABLE_ERROR'
export const GET_TIMETABLE_SUCCESS = 'GET_TIMETABLE_SUCCESS'
export const SET_TIMETABLE_DAY_ACTIVE= 'SET_TIMETABLE_DAY_ACTIVE'
export const SET_TIMETABLE_DAYACTION="SET_TIMETABLE_DAYACTION"
export const SET_TIMETABLE_DAYACTION_START="SET_TIMETABLE_DAYACTION_START"
export const SET_DATE="SET_DATE"

export  const url = Platform.select({
  ios:"localhost",
  android:'192.168.43.179',
  // android:'10.0.2.2'
})